#!/usr/bin/python3
import sys
import numpy as sci_lib
import time
from ev3dev.dev import *
egtim_seti=[[0,0],[0,1],[1,0],[1,1]]
cikis=[0,1,1,0]
n=0.5
def bias_random():
    bias_degerleri=[]
    bias_degerleri=sci_lib.random.uniform(low=-1.0,high=1.0,size=(1,3))
    return bias_degerleri
def agirlik_random():
    agirlik_degerleri=[]
    agirlik_degerleri=sci_lib.random.uniform(low=-0.5,high=0.5,size=(1,6))
    return agirlik_degerleri

def func_sigmoid(net):
    return 1 / (1 + sci_lib.exp(-net))

a=agirlik_random()
b=bias_random()

w13 = a[0][0]
w14 = a[0][1]
w23 = a[0][2]
w24 = a[0][3]
w35 = a[0][4]
w45 = a[0][5]

b3 = b[0][0]
b4 = b[0][1]
b5 = b[0][2]



for iterasyon in range(0,10000):

    
    for i in range(0,4):
        O1=egtim_seti[i][0]
        O2=egtim_seti[i][1]

        net3=(O1*w13)+(O2*w23)+b3
        O3=func_sigmoid(net3)
        net4=(O1*w14)+(O2*w24)+b4
        O4=func_sigmoid(net4)

        net5=(O3*w35)+(O4*w45)+b5
        O5=func_sigmoid(net5)

        s5=(cikis[i]-O5)*O5*(1-O5)

        d35=n*s5*O3
        w35=w35+d35
        d45=n*s5*O4
        w45=w45+d45

        b5=b5+(n*s5)

        s3=O3*(1-O3)*(w35*s5)
        s4=O4*(1-O4)*(w45*s5)

        b3=b3+(n*s3)
        b4=b4+(n*s4)

        d13=n*s3*O1
        w13=w13+d13
        d14=n*s4*O1
        w14=w14+d14
        d23=n*s3*O2
        w23=w23+d23
        d24=n*s4*O2
        w24=w24+d24
        print(s5)
      







while(True):

    Q1=TouchSensor('in1') 
    Q2=TouchSensor('in2')

    

    net3=(Q1*w13)+(Q2*w23)+b3
    Q3=func_sigmoid(net3)
    net4=(Q1*w14)+(Q2*w24)+b4
    Q4=func_sigmoid(net4)


    net5=(Q3*w35)+(Q4*w45)+b5
    Q5=func_sigmoid(net5)

    time.sleep(5) #5sn bekleme yapar











